/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialDealsRouteImport } from './routes/special-deals'
import { Route as SalesAnomaliesRouteImport } from './routes/sales-anomalies'
import { Route as RateShopRouteImport } from './routes/rate-shop'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as IndexRouteImport } from './routes/index'

const SpecialDealsRoute = SpecialDealsRouteImport.update({
  id: '/special-deals',
  path: '/special-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesAnomaliesRoute = SalesAnomaliesRouteImport.update({
  id: '/sales-anomalies',
  path: '/sales-anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const RateShopRoute = RateShopRouteImport.update({
  id: '/rate-shop',
  path: '/rate-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/rate-shop': typeof RateShopRoute
  '/sales-anomalies': typeof SalesAnomaliesRoute
  '/special-deals': typeof SpecialDealsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/rate-shop': typeof RateShopRoute
  '/sales-anomalies': typeof SalesAnomaliesRoute
  '/special-deals': typeof SpecialDealsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/rate-shop': typeof RateShopRoute
  '/sales-anomalies': typeof SalesAnomaliesRoute
  '/special-deals': typeof SpecialDealsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contracts'
    | '/rate-shop'
    | '/sales-anomalies'
    | '/special-deals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contracts' | '/rate-shop' | '/sales-anomalies' | '/special-deals'
  id:
    | '__root__'
    | '/'
    | '/contracts'
    | '/rate-shop'
    | '/sales-anomalies'
    | '/special-deals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractsRoute: typeof ContractsRoute
  RateShopRoute: typeof RateShopRoute
  SalesAnomaliesRoute: typeof SalesAnomaliesRoute
  SpecialDealsRoute: typeof SpecialDealsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/special-deals': {
      id: '/special-deals'
      path: '/special-deals'
      fullPath: '/special-deals'
      preLoaderRoute: typeof SpecialDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-anomalies': {
      id: '/sales-anomalies'
      path: '/sales-anomalies'
      fullPath: '/sales-anomalies'
      preLoaderRoute: typeof SalesAnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-shop': {
      id: '/rate-shop'
      path: '/rate-shop'
      fullPath: '/rate-shop'
      preLoaderRoute: typeof RateShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractsRoute: ContractsRoute,
  RateShopRoute: RateShopRoute,
  SalesAnomaliesRoute: SalesAnomaliesRoute,
  SpecialDealsRoute: SpecialDealsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
